name: API Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Step 2: Set up Java environment
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # ✅ Step 3: Install dependencies
      - name: Install Dependencies
        run: mvn clean install -DskipTests

      # ✅ Step 4: Run API Tests
      - name: Run Tests
        run: mvn test

      # ✅ Step 5: Upload test reports (Updated to v4)
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/
